SELECT TBIL_POL_PRM_SA_LC, TBIL_CLAIM_REPTED.*, TBIL_POLICY_PREM_INFO.*, TBIL_POLICY_DET.*, tbil_ins_detail.*, TBIL_POL_PRM_SA_LC,  TBIL_POLY_ASSRD_CD, TBIL_INSRD_SURNAME +' '+ RTRIM(ISNULL(TBIL_INSRD_FIRSTNAME, '')) AS 'ASSURED NAME', TBIL_CLAIM_PAID.TBIL_CLM_PAID_AMT_LC, TBIL_CLM_PAID_SA_AMT_LC, ((TBIL_POL_PRM_SA_LC * 25)/100) AS 'COMP_PARTIAL_CLAIM'
  FROM [ABS_LIFE].[dbo].[TBIL_CLAIM_REPTED] inner join TBIL_POLICY_PREM_INFO ON TBIL_CLM_RPTD_POLY_NO = TBIL_POL_PRM_POLY_NO INNER JOIN TBIL_POLICY_DET ON TBIL_POLY_POLICY_NO = TBIL_CLM_RPTD_POLY_NO INNER JOIN tbil_ins_detail ON TBIL_POLY_ASSRD_CD = TBIL_INSRD_CODE INNER JOIN TBIL_CLAIM_PAID ON TBIL_CLM_PAID_POLY_NO=TBIL_CLAIM_REPTED.TBIL_CLM_RPTD_POLY_NO
  WHERE TBIL_CLM_RPTD_CLM_NO= '8920238'
  
  
GO
