--SELECT SUM(TBFN_TRANS_TOT_AMT) AS TRANS_TOT_AMT      
--  FROM [ABS_LIFE].[dbo].[TBFN_ALLOC_DETAIL]
--  where TBFN_TRANS_POLY_NO='POL/2011/5001/CICCB001-1/00043' and (TBFN_TRANS_TYPE='N') OR (TBFN_TRANS_TYPE='L') OR (TBFN_TRANS_TYPE='I')


UPDATE TBIL_CLAIM_PAID SET TBIL_CLM_PAID_CONTRIB_AMT_LC=(SELECT SUM(TBFN_TRANS_TOT_AMT) AS TRANS_TOT_AMT      
  FROM [ABS_LIFE].[dbo].[TBFN_ALLOC_DETAIL]
  where TBFN_TRANS_POLY_NO='POL/2011/5001/CICCB001-1/00043' and (TBFN_TRANS_TYPE='N') OR (TBFN_TRANS_TYPE='L') OR (TBFN_TRANS_TYPE='I'))
  WHERE TBIL_CLM_PAID_POLY_NO='POL/2011/5001/CICCB001-1/00043'
  
  SELECT TBIL_CLM_PAID_CONTRIB_AMT_LC AS 'CONTRIBUTION CLAIM' FROM TBIL_CLAIM_PAID WHERE TBIL_CLM_PAID_POLY_NO='POL/2011/5001/CICCB001-1/00043'
GO


