USE [ABS_LIFE]
GO

/****** Object:  StoredProcedure [dbo].[SPIL_PRG_LI_CLM_MATURE_ENDOWMENT]    Script Date: 08/07/2015 09:05:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SPIL_PRG_LI_CLM_MATURE_ENDOWMENT]
@pPOLICY_NUMBER nvarchar(35), @pPRODUCT_CODE nvarchar(35), @pBONUS_RT_YEAR INT
--, @pCLAIM_NUMBER nvarchar(35)
AS
BEGIN
DECLARE @pSUM_ASSURED numeric(18, 2), @pBONUS_AMOUNT numeric(18, 2), @pPROD_PAY_MULTIPLE VARCHAR(1), @pPREM_BONUS_CD VARCHAR(1)

SELECT @pPROD_PAY_MULTIPLE = (SELECT TBIL_PRDCT_SA_PAY_MULITIPLE FROM TBIL_PRODUCT_DETL WHERE TBIL_PRDCT_DTL_CODE = @pPRODUCT_CODE)

IF	@pPROD_PAY_MULTIPLE='Y'
BEGIN
SELECT @pSUM_ASSURED =(SELECT ((SUM(TBIL_POL_PRM_SA_LC)*50)/100) FROM TBIL_POLICY_PREM_INFO WHERE TBIL_POL_PRM_POLY_NO = @pPOLICY_NUMBER)

--SELECT @pSUM_ASSURED AS 'SUM ASSURED_Y'
END
ELSE
BEGIN
SELECT @pSUM_ASSURED =(SELECT SUM(TBIL_POL_PRM_SA_LC) FROM TBIL_POLICY_PREM_INFO WHERE TBIL_POL_PRM_POLY_NO = @pPOLICY_NUMBER)
--SELECT @pSUM_ASSURED AS 'SUM ASSURED'
END


SELECT @pPREM_BONUS_CD = (SELECT TBIL_POL_PRM_RT_BONUS_CD FROM TBIL_POLICY_PREM_INFO WHERE TBIL_POL_PRM_POLY_NO = @pPOLICY_NUMBER)
DECLARE @pPREMIUM_YRS INT
SELECT @pPREMIUM_YRS = (SELECT TBIL_POL_PRM_PERIOD_YRS FROM TBIL_POLICY_PREM_INFO WHERE TBIL_POL_PRM_POLY_NO = @pPOLICY_NUMBER)

IF @pPREM_BONUS_CD='Y'
BEGIN
SELECT @pBONUS_AMOUNT = (SELECT @pSUM_ASSURED * @pPREMIUM_YRS * TBIL_BONUS_RATE * TBIL_BONUS_RATE_PER FROM TBIL_BONUS_INTREST WHERE TBIL_BONUS_RT_YEAR = @pBONUS_RT_YEAR)

END
ELSE
BEGIN
SELECT @pBONUS_AMOUNT = (SELECT @pSUM_ASSURED * @pPREMIUM_YRS * TBIL_BONUS_RATE * TBIL_BONUS_RATE_PER AS 'BONUS' FROM TBIL_BONUS_INTREST WHERE TBIL_BONUS_RT_YEAR = @pBONUS_RT_YEAR)
END

--SELECT @pPREM_BONUS_CD AS 'BONUS CODE'


CREATE TABLE #ENDOWMENT(
POLICY_NUMBER nvarchar(35), SUM_ASSURED  NUMERIC(18, 2), BONUS_AMOUNT NUMERIC(18, 2)
)

INSERT INTO  #ENDOWMENT VALUES (@pPOLICY_NUMBER, @pSUM_ASSURED, @pBONUS_AMOUNT)
--SELECT * FROM #ENDOWMENT

UPDATE TBIL_CLAIM_PAID SET TBIL_CLM_PAID_BONUS_AMT_LC = @pBONUS_AMOUNT, TBIL_CLM_PAID_BONUS_AMT_FC = @pBONUS_AMOUNT, TBIL_CLM_PAID_SA_AMT_LC = @pSUM_ASSURED, TBIL_CLM_PAID_SA_AMT_FC = @pSUM_ASSURED WHERE (TBIL_CLM_PAID_POLY_NO = @pPOLICY_NUMBER) 


--SELECT * FROM #ENDOWMENT
SELECT * FROM TBIL_CLAIM_PAID WHERE (TBIL_CLM_PAID_POLY_NO = @pPOLICY_NUMBER) 

DROP TABLE #ENDOWMENT

END

GO


