SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPIL_SELPOLNUM_TBIL_POLICY_DET] 
	
	@TBIL_POLY_POLICY_NO varchar(40)
AS
BEGIN
		SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT * fROM [dbo].[TBIL_POLICY_DET] where TBIL_POLY_POLICY_NO=@TBIL_POLY_POLICY_NO
	
END
GO
