USE [ABS_LIFE]
GO

/****** Object:  StoredProcedure [dbo].[SPIL_GET_CLAIM_PAID]    Script Date: 08/04/2015 10:56:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[SPIL_GET_CLAIM_PAID]
			@pTBIL_CLM_PAID_MDLE char(3) 
           ,@pTBIL_CLM_PAID_POLY_NO nchar(50)
           ,@pTBIL_CLM_PAID_CLM_NO nchar(50)
           ,@pTBIL_CLM_PAID_UNDW_YR nvarchar(10)
           ,@pTBIL_CLM_PAID_PRDCT_CD nchar(10)
           ,@pTBIL_CLM_PAID_CLM_TYP nchar(10)
           ,@pTBIL_CLM_PAID_POLY_FROM_DT datetime
           ,@pTBIL_CLM_PAID_POLY_TO_DT datetime
           ,@pTBIL_CLM_PAID_DUE_DATE datetime
AS
BEGIN

	SET NOCOUNT ON;

IF EXISTS(SELECT * FROM TBIL_CLAIM_PAID WHERE TBIL_CLM_PAID_POLY_NO=@pTBIL_CLM_PAID_POLY_NO)
BEGIN 
SELECT TBIL_CLAIM_PAID.*, TBIL_PRDCT_DTL_CAT FROM TBIL_CLAIM_PAID INNER JOIN TBIL_PRODUCT_DETL ON TBIL_PRDCT_DTL_CODE=TBIL_CLM_PAID_PRDCT_CD
 WHERE TBIL_CLM_PAID_POLY_NO=@pTBIL_CLM_PAID_POLY_NO
END 
ELSE
BEGIN
INSERT INTO TBIL_CLAIM_PAID(TBIL_CLM_PAID_MDLE, TBIL_CLM_PAID_CLM_NO, TBIL_CLM_PAID_POLY_NO, TBIL_CLM_PAID_UNDW_YR,TBIL_CLM_PAID_PRDCT_CD,TBIL_CLM_PAID_CLM_TYP,TBIL_CLM_PAID_POLY_FROM_DT,TBIL_CLM_PAID_POLY_TO_DT,TBIL_CLM_PAID_DUE_DATE) 
           VALUES(@pTBIL_CLM_PAID_MDLE, @pTBIL_CLM_PAID_CLM_NO, @pTBIL_CLM_PAID_POLY_NO, @pTBIL_CLM_PAID_UNDW_YR ,@pTBIL_CLM_PAID_PRDCT_CD ,@pTBIL_CLM_PAID_CLM_TYP ,@pTBIL_CLM_PAID_POLY_FROM_DT ,@pTBIL_CLM_PAID_POLY_TO_DT,@pTBIL_CLM_PAID_DUE_DATE
  )
           

SELECT TBIL_CLAIM_PAID.*, TBIL_PRDCT_DTL_CAT FROM TBIL_CLAIM_PAID INNER JOIN TBIL_PRODUCT_DETL ON TBIL_PRDCT_DTL_CODE=TBIL_CLM_PAID_PRDCT_CD
 WHERE  TBIL_CLM_PAID_POLY_NO=@pTBIL_CLM_PAID_POLY_NO


END
END 


GO


